version: "3"

services:
  backend:
    build:
      context: .
    image: backend
    container_name: backend
    hostname: backend
    restart: on-failure
    volumes:
      - .:/workspace
    command: > 
      sh -c "sleep infinity"
    networks:
      - shared_network

  db:
    image: postgres:10-alpine
    container_name: db
    hostname: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - shared_network

  phppgadmin:
    image: docker.io/bitnami/phppgadmin
    ports:
        - '0.0.0.0:8081:8080'
    volumes:
        - pgadmin:/var/lib/pgadmin
    environment: 
        - DATABASE_HOST=db
    depends_on:
        - db
    networks:
        - shared_network

volumes:
  postgres-data:
  pgadmin:

networks:
    shared_network:
        driver: bridge